"""Motor quantitativo - validacao OHLC + transform + filtros + regime.

Módulo principal que exporta:
- F1: Validação e transformação OHLC
- F2: Filtros de qualidade (spread, ADF, TR, Parkinson)
- F3: Regime (Hurst, OU, Bootstrap θ)
- F4: Volatilidade (GARCH, Z, percentil)
- F5: Sinal (confirmação, força, payload)
"""

__version__ = "0.1.0"

# Importar OHLC (F1)
from motor.ohlc import (
    validate_bar,
    validate_bars_sequence,
    validate_timestamp_utc,
    validate_price_integrity,
    validate_order_temporal,
    handle_gaps,
    validate_ohlc_format,
    ValidationError,
    BarStatus,
    ValidatedBar,
    ValidatedSeries,
    sync_instruments,
    SyncResult,
    transform_to_returns,
    transform_to_returns_dict,
    TransformResult,
    calculate_mid_price,
    calculate_log_price,
    calculate_log_return,
)

# Importar filtros (F2)
from motor.filters import (
    FilterSpread,
    FilterSpreadResult,
    FilterADF,
    FilterADFResult,
    FilterTR,
    FilterTRResult,
    FilterParkinson,
    FilterParkinsonResult,
    Pipeline,
    PipelineResult,
    FilterStatus,
)

# Importar regime (F3)
from motor.regime import (
    calculate_hurst,
    HurstResult,
    HurstStatus,
    RegimeType,
    estimate_ou_kalman,
    estimate_ou_mle,
    OUEstimationResult,
    OUStatus,
    bootstrap_theta,
    BootstrapResult,
    BootstrapStatus,
    F3Pipeline,
    F3PipelineResult,
    F3Status,
)

# Importar vol (F4)
from motor.vol import (
    GARCHResult,
    GARCHStatus,
    estimate_garch,
    estimate_garch_with_fallback,
    ZScoreResult,
    ZScoreStatus,
    calculate_zscore,
    PercentilResult,
    PercentilStatus,
    calculate_percentil_z,
    F4Pipeline,
    F4PipelineResult,
    F4Status,
    run_f4_pipeline,
)

# Importar signal (F5)
from motor.signal import (
    ConfirmacaoResult,
    ConfirmacaoStatus,
    ConfirmacaoDirection,
    calculate_confirmacao,
    ConfirmacaoMetrics,
    Direction,
    Confidence,
    ForcaResult,
    ForcaStatus,
    calcular_forca,
    ConfidenceLevel,
    classificar_confianca,
    PayloadMotor,
    SinalQuantitativo,
    EstatisticasModelo,
    RiscosEstatisticos,
    CalibracaoAdaptativa,
    criar_payload_neutro,
    montar_payload,
    F5Pipeline,
    F5PipelineResult,
    F5Status,
    run_f5_pipeline,
)

# Importar backtest (F6 - motor only)
from motor.backtest import (
    # Constants
    F6_INSTRUMENTS,
    F6_FORCE_THRESHOLD,
    F6_TIMEFRAME,
    SHARPE_GATE_THRESHOLD,
    SHARPE_GATE_MIN_INSTRUMENTS,
    TARGET_SHARPE,
    TARGET_WR,
    TARGET_PF,
    TARGET_MAXDD,
    # Classes and functions
    BacktestLoader,
    LoaderResult,
    LoaderStatus,
    InstrumentBars,
    load_historical_data,
    load_fixture_data,
    BarRunner,
    BacktestResult,
    RunResult,
    RunnerStatus,
    run_backtest,
    PnLCalculator,
    PnLResult,
    Trade,
    Position,
    TradeStatus,
    calculate_pnl,
    run_pnl_simulation,
    InstrumentMetrics,
    GateResult,
    MetricsCalculator,
    check_gate,
    calculate_sharpe_from_equity,
    BacktestReport,
    InstrumentReport,
    ReportBuilder,
    Veredito,
    build_backtest_report,
    F6Pipeline,
    PipelineResult,
    PipelineOutput,
    PipelineStatus,
    run_f6_pipeline,
)

__all__ = [
    # OHLC validation (F1)
    "validate_bar",
    "validate_bars_sequence",
    "validate_timestamp_utc",
    "validate_price_integrity",
    "validate_order_temporal",
    "handle_gaps",
    "validate_ohlc_format",
    "ValidationError",
    "BarStatus",
    "ValidatedBar",
    "ValidatedSeries",
    # Sync (F1)
    "sync_instruments",
    "SyncResult",
    # Transform (F1)
    "transform_to_returns",
    "transform_to_returns_dict",
    "TransformResult",
    "calculate_mid_price",
    "calculate_log_price",
    "calculate_log_return",
    # Filters (F2)
    "FilterSpread",
    "FilterSpreadResult",
    "FilterADF",
    "FilterADFResult",
    "FilterTR",
    "FilterTRResult",
    "FilterParkinson",
    "FilterParkinsonResult",
    "Pipeline",
    "PipelineResult",
    "FilterStatus",
    # Regime (F3)
    "calculate_hurst",
    "HurstResult",
    "HurstStatus",
    "RegimeType",
    "estimate_ou_kalman",
    "estimate_ou_mle",
    "OUEstimationResult",
    "OUStatus",
    "bootstrap_theta",
    "BootstrapResult",
    "BootstrapStatus",
    "F3Pipeline",
    "F3PipelineResult",
    "F3Status",
    # Vol (F4)
    "GARCHResult",
    "GARCHStatus",
    "estimate_garch",
    "estimate_garch_with_fallback",
    "ZScoreResult",
    "ZScoreStatus",
    "calculate_zscore",
    "PercentilResult",
    "PercentilStatus",
    "calculate_percentil_z",
    "F4Pipeline",
    "F4PipelineResult",
    "F4Status",
    "run_f4_pipeline",
    # Signal (F5)
    "ConfirmacaoResult",
    "ConfirmacaoStatus",
    "ConfirmacaoDirection",
    "calculate_confirmacao",
    "ConfirmacaoMetrics",
    "Direction",
    "Confidence",
    "ForcaResult",
    "ForcaStatus",
    "calcular_forca",
    "ConfidenceLevel",
    "classificar_confianca",
    "PayloadMotor",
    "SinalQuantitativo",
    "EstatisticasModelo",
    "RiscosEstatisticos",
    "CalibracaoAdaptativa",
    "criar_payload_neutro",
    "montar_payload",
    "F5Pipeline",
    "F5PipelineResult",
    "F5Status",
    "run_f5_pipeline",
    # Backtest (F6 - motor only)
    "F6_INSTRUMENTS",
    "F6_FORCE_THRESHOLD",
    "F6_TIMEFRAME",
    "SHARPE_GATE_THRESHOLD",
    "SHARPE_GATE_MIN_INSTRUMENTS",
    "TARGET_SHARPE",
    "TARGET_WR",
    "TARGET_PF",
    "TARGET_MAXDD",
    "BacktestLoader",
    "LoaderResult",
    "LoaderStatus",
    "InstrumentBars",
    "load_historical_data",
    "load_fixture_data",
    "BarRunner",
    "BacktestResult",
    "RunResult",
    "RunnerStatus",
    "run_backtest",
    "PnLCalculator",
    "PnLResult",
    "Trade",
    "Position",
    "TradeStatus",
    "calculate_pnl",
    "run_pnl_simulation",
    "InstrumentMetrics",
    "GateResult",
    "MetricsCalculator",
    "check_gate",
    "calculate_sharpe_from_equity",
    "BacktestReport",
    "InstrumentReport",
    "ReportBuilder",
    "Veredito",
    "build_backtest_report",
    "F6Pipeline",
    "PipelineResult",
    "PipelineOutput",
    "PipelineStatus",
    "run_f6_pipeline",
]